name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production

    steps:
    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Install SSH key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

    - name: SSH into server, create temporary directory, and clone repository
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
          if [ -d "temp_repo" ]; then
            rm -rf temp_repo
          fi
          mkdir temp_repo
          cd temp_repo
          git clone https://github.com/kakage553656552/websocket.git
          cd websocket
          npm install
          npm run build
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
