name: Deploy to Windows Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Windows Server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            # Clean the deployment directory on Windows Server
            Remove-Item -Recurse -Force /c/deploy-temp/*

            # Copy repository files to the deployment directory
            scp -r ./* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:/c/deploy-temp/

            # Navigate to the deployment directory
            cd /c/deploy-temp
            
            # Pull the latest code, install dependencies, and build
            git pull
            npm install
            npm run build

            # Move the build artifacts to the Nginx html directory
            Remove-Item -Recurse -Force /c/nginx/html/*
            Move-Item /c/deploy-temp/dist/* /c/nginx/html

            # Reload or restart Nginx to apply the changes
            # This assumes that your service name is 'nginx'
            Restart-Service nginx