name: Deploy to Nginx Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > $env:USERPROFILE\.ssh\id_rsa && icacls $env:USERPROFILE\.ssh\id_rsa /inheritance:r && icacls $env:USERPROFILE\.ssh\id_rsa /grant:r "%USERNAME%":F

      - name: Deploy to Nginx server
        run: |
          ssh -o StrictHostKeyChecking=no -i $env:USERPROFILE\.ssh\id_rsa Administrator@120.46.34.178 "cd C:\nginx\html && git pull"

